#!/usr/bin/env python3

""" Async Comprehensions """

from typing import List
from async_generator_module import async_generator

async def async_comprehension() -> List[float]:
    """
    Collects 10 random numbers generated by async_generator using an async comprehension.

    Returns:
        List[float]: A list of 10 random float numbers between 0 and 10.
    """
    return [i async for i in async_generator()]
